name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm install
        npm run build
        ./node_modules/.bin/firebase deploy --project dsc-logo-generator --debug --only hosting --token "$FIREBASE_TOKEN"
      env:
        CI: true
